## The Basics of NumPy Arrays

> Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

Python中的數據操作基本就是NumPy數組操作的同義詞：一些新的工具像Pandas 都是依賴於NumPy數組建立起來的。本節會展示使用NumPy數組操作和訪問數據以及子數組的一些例子，包括切分、變形和組合。儘管這裡展示的操作有些枯燥和學術化，但是它們是組成本書後面使用的例子的基礎。你應該更好的掌握它們。


> - *Attributes*: Determining the size, shape, memory consumption, and data types of arrays
> - *Indexing & Slicing*: Getting and setting the value of individual array elements
> - *Reshaping*: Changing the shape of a given array
> - *Joining & Splitting*: Combining multiple arrays into one, and splitting one array into many

### 2.NumPy :  Indexing & Slicing  數組切片

> Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the *slice* notation, marked by the colon (``:``) character.
The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array ``x``, use this: If any of these are unspecified, they default to the values ``start=0``, ``stop=``*``size of dimension``*, ``step=1``.

正如我們可以使用中括號獲取單個元素值，我們也可以使用中括號的*切片*語法獲取子數組，切片的語法遵從標準Python列表的切片語法格式；對於一個數組`x`進行切片：如果三個參數沒有設置值的話，默認值分別是`start=0`，`stop=`*`維度的長度`*，`step=1`。 x[start:stop:step]


In [1]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[5]
arr[5:8]

array([5, 6, 7])

In [2]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[0] = 123
arr[5:8] = 12
arr[:] = 64
arr

array([64, 64, 64, 64, 64, 64, 64, 64, 64, 64])

-  arange(x) : One-dimensional subarrays 一維子數組

In [3]:
x = np.arange(10)     #[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x[:5]  # 前五個元素 ([0, 1, 2, 3, 4])
x[5:]  # 後五個元素 ([5, 6, 7, 8, 9])
x[4:7] # 在 4-7 中間

array([4, 5, 6])

In [5]:
x[::2]  # 每隔一個取元素  ([0, 2, 4, 6, 8])
x[1::2] # 每隔一個取元素  ([1, 3, 5, 7, 9])

array([1, 3, 5, 7, 9])

In [6]:
x[::-1]    # 反序數組   ([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])
x[5::-2]   # 從序號5開始向前取元素  ([5, 3, 1])

array([5, 3, 1])

In [7]:
s = 'hello world'   # String reverse
s[:]
s[::-1]

'dlrow olleh'

- Multi-dimensional subarrays 多維子數組

In [8]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]
arr2d[0][2]
arr2d[0, 2]

3

In [9]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:2, :3]      # 行的維度取前兩個，列的維度取前三個，形狀變為(2, 3)
arr2d[:3, ::2]     # 行的維度取前三個（全部），列的維度每個一個取一列，形狀變為(3, 2)
arr2d[::-1, ::-1]  # 行和列都反轉，形狀保持(3, 4)

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [10]:
arr2d[:, 0]     # x2的第一列  ([1, 4, 7])
arr2d[0, :]     # x2的第一行  ([1, 2, 3])

array([1, 2, 3])

In [11]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0]
arr3d[1, 0]

array([7, 8, 9])