# Matrix multiplication
Since NumPy arrays are basically vectors and matrices, it makes sense that there are functions for dot products and matrix multiplication. Specifically, the main function to use is np.matmul, which takes two vector/matrix arrays as input and produces a dot product or matrix multiplication.

The code below shows various examples of matrix multiplication. When both inputs are 1-D, the output is the dot product.

Note that the dimensions of the two input matrices must be valid for a matrix multiplication. Specifically, the second dimension of the first matrix must equal the first dimension of the second matrix, otherwise np.matmul will result in a ValueError.

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([-3, 0, 10])
print(np.matmul(arr1, arr2))

arr3 = np.array([[1, 2], [3, 4], [5, 6]])
arr4 = np.array([[-1, 0, 1], [3, 2, -4]])
print(repr(np.matmul(arr3, arr4)))
print(repr(np.matmul(arr4, arr3)))
#print(repr(np.matmul(arr3, arr3))) # This will result in ValueError

27
array([[  5,   4,  -7],
       [  9,   8, -13],
       [ 13,  12, -19]])
array([[  4,   4],
       [-11, -10]])


## Numerical Operation in Numpy
### Statistics

In [29]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [30]:
y.mean()

3.0

In [31]:
np.median(x)

1.5

In [32]:
np.median(y, axis=-1) # last axis

array([2., 5.])

In [33]:
x.std()          # full population standard dev.

0.82915619758885

In [34]:
y.std()

1.9148542155126762

## Funciones Universales Binarias

### Son funciones que realizan operaciones elemento-a-elemento sobre datos en una   `ndarray`.  Las funciones _binarias_ toman dos arrays y devuelven uno o más arrays.

|Función|Descripción|
|-------|-----------|
|`add`|Suma entre elementos correspondientes entre arrays|
|`subtract`|Resta entre elementos de arrays|
|`multiply`|Multiplica arrays|
|`divide`, `floor_divide`|Divide o división truncada|
|`array_equal`|Devuelve `True` si los elementos del array son iguales entre sí|
|`power`|Eleva cada elemento del primer array a la potencia indicada en el segundo array|
|`fmin`|Devuelve el mínimo entre cada elemento. `fmin` ignora los `NaN`|
|`fmax`|Devuelve el máximo entre cada elemento. `fmax` ignora los `NaN`|


In [35]:
import numpy as np

arr = np.array([5,36,17,18,9])

arr_2 = np.array([8,24,17,19,9])

In [36]:
np.add(arr,arr_2)
np.subtract(arr,arr_2)
np.multiply(arr,arr_2)
np.divide(arr,arr_2)
np.array_equal(arr,arr_2)
np.fmin(arr,arr_2)
np.fmax(arr,arr_2)

array([ 8, 36, 17, 19,  9])

In [37]:
import numpy as np

arr = np.arange(0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.23445582, 0.26653842, 0.12572834],
       [0.25010229, 0.03324453, 0.02416149],
       [0.88455445, 0.76037819, 0.13973833],
       [0.25167849, 0.90903415, 0.38220419]])

In [39]:
arr_ent = np.random.randint(100, size=(2,3))
arr_ent

array([[44, 99, 57],
       [15, 59, 94]])

In [40]:
arr_6 = np.full((3,3),6)
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [41]:
np.append(arr, [12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [42]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
np.delete(arr_ent,0,axis=1)

array([[99, 57],
       [59, 94]])

## Mathematical and Statistical Methods

In [44]:
import numpy as np
data = np.random.randn(6, 3)
data

array([[ 1.53236483,  0.58692537,  0.78494972],
       [ 0.04972455,  1.27051515, -0.70445055],
       [-1.44427245, -0.4656622 , -0.79012843],
       [ 1.09596167,  0.80382464, -0.58788268],
       [-0.04644753, -0.47055033,  0.82633891],
       [ 0.85750403, -0.01989238, -0.96191195]])

In [45]:
data.mean()

0.12871724329204323

In [46]:
data.min()

-1.4442724505889528

In [47]:
data.max()

1.5323648314693674

In [48]:
data.sum()

2.316910379256778

In [49]:
data.sum(axis = 0)

array([ 2.0448351 ,  1.70516026, -1.43308497])

## Values

In [50]:
values = np.arange(5)
values

array([0, 1, 2, 3, 4])

In [51]:
values.cumsum()

array([ 0,  1,  3,  6, 10])

In [52]:
values.std()

1.4142135623730951

In [53]:
matrix_array= np.array([np.arange(1, 5), np.arange(6, 10 ), np.arange(11, 15)])
matrix_array

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [54]:
matrix_array.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 7,  9, 11, 13],
       [18, 21, 24, 27]])

In [55]:
matrix_array.cumsum(axis=1)

array([[ 1,  3,  6, 10],
       [ 6, 13, 21, 30],
       [11, 23, 36, 50]])

In [56]:
matrix_array.cumprod(axis=1)

array([[    1,     2,     6,    24],
       [    6,    42,   336,  3024],
       [   11,   132,  1716, 24024]])

#### Write a NumPy program to convert an array to a float type.
```
Original array 
[1, 2, 3, 4] 
Array converted to a float type: 
[ 1. 2. 3. 4.] 
```

In [57]:
import numpy as np
a = [1, 2, 3, 4]
print("Original array")
print(a)
x = np.asfarray(a)
print("Array converted to a float type:")
print(x)

Original array
[1, 2, 3, 4]
Array converted to a float type:
[1. 2. 3. 4.]


#### Write a NumPy program to construct an array by repeating.
```
Original array 
[1, 2, 3, 4] 
Repeating 2 times 
[1 2 3 4 1 2 3 4]
Repeating 3 times 
[1 2 3 4 1 2 3 4 1 2 3 4]
```

In [58]:
n=3
x = np.tile(a, n)
x

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

#### How to tell if a given 2D array has null columns?

In [59]:
nums = np.random.randint(0,3,(4,10))
print(nums)
print("Test whether the said array has null columns or not:")
print((~nums.any(axis=0)).any())

[[2 1 2 0 0 0 1 1 1 1]
 [1 2 2 1 0 0 0 2 1 1]
 [0 1 2 1 0 1 0 1 1 1]
 [1 1 1 0 1 2 0 1 1 0]]
Test whether the said array has null columns or not:
False


#### Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? 
```
a= [
[1,2,3]
]

b= [
[4],
[5],
[6],
]

Expected Output = [[5 6 7]
                   [6 7 8]
                   [7 8 9]]
```


In [60]:
A = np.arange(1,4).reshape(3,1)
B = np.arange(4,7).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[5 6 7]
 [6 7 8]
 [7 8 9]]


##### Solve the linear equation
##### 10x+4y = 3 
#####  -x+5y = 2 

In [61]:
A = np.array([[10, 4], [-1, 5]])
b = np.array([3,2])
x = np.linalg.solve(A, b)
x

array([0.12962963, 0.42592593])

##### Create a 4x4 matrix with random values and find inverse of it.

In [62]:
x= np.random.random((4,4))
print(x)
print("Inverse")
y = np.linalg.inv(x) 
print(y)

[[0.06423033 0.38420169 0.88963786 0.76388023]
 [0.01768124 0.66339348 0.81355441 0.2798899 ]
 [0.63429039 0.44389191 0.03804707 0.76503384]
 [0.8806063  0.17662332 0.57386344 0.7404968 ]]
Inverse
[[-1.32700006  0.51740982 -0.15549573  1.33398393]
 [-0.924363    1.49969141  1.11682187 -0.76712334]
 [ 0.22338188  0.44968438 -1.19893345  0.83825553]
 [ 1.62544657 -1.32150774  0.84767121 -0.70259181]]


##### Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array. 

##### Expected Output:
#### Original Array:
```
['python' 'PHP' 'java' 'C++']

Capitalized: ['Python' 'Php' 'Java' 'C++']
Lowered: ['python' 'php' 'java' 'c++']
Uppered: ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased: ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased: ['Python' 'Php' 'Java' 'C++']

```

In [63]:
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)
print("Original Array:")
print(x)
capitalized_case = np.char.capitalize(x)
lowered_case = np.char.lower(x)
uppered_case = np.char.upper(x)
swapcased_case = np.char.swapcase(x)
titlecased_case = np.char.title(x)
print("\nCapitalized: ", capitalized_case)
print("Lowered: ", lowered_case)
print("Uppered: ", uppered_case)
print("Swapcased: ", swapcased_case)
print("Titlecased: ", titlecased_case)

Original Array:
['python' 'PHP' 'java' 'C++']

Capitalized:  ['Python' 'Php' 'Java' 'C++']
Lowered:  ['python' 'php' 'java' 'c++']
Uppered:  ['PYTHON' 'PHP' 'JAVA' 'C++']
Swapcased:  ['PYTHON' 'php' 'JAVA' 'c++']
Titlecased:  ['Python' 'Php' 'Java' 'C++']


/var/folders/9q/486czkcn7lv5v0hwbt71twdc0000gn/T/ipykernel_4551/3400659836.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array(['python', 'PHP', 'java', 'C++'], dtype=np.str)


##### Write a NumPy program to split the element of a given array with spaces
```
Original Array:
 ['apple mangoes peach grapes']
Output
[list(['apple', 'mangoes', 'peach', 'grapes'])]
```

In [64]:
x= np.array(['apple mangoes peach grapes'])
r = np.char.split(x)
print("\nSplit the element of the said array with spaces: ")
print(r)


Split the element of the said array with spaces: 
[list(['apple', 'mangoes', 'peach', 'grapes'])]


##### Write a NumPy program to flatten the array and then find its median.
```
[[ 0 1 2 3 4 5]
[ 6 7 8 9 10 11]]
```

In [65]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
flat=x.flatten()
print(flat)
np.median(flat)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


5.5

##### Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
```
Original array:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

80th percentile for all elements of the said array along the second axis:
[ 4. 10.]
```

In [66]:
x= np.array([[0,1,2,3,4,5],[6,7,8,9,10,11]])
np.percentile(x,80,axis=1)

array([ 4., 10.])

In [67]:
import numpy as np
array_4 = np.array(list(range(10)))
array_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
array_5 = np.array(list(range(15)), dtype = np.int32)
array_5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
      dtype=int32)