## The Basics of NumPy Arrays

> Data manipulation in Python is nearly synonymous with NumPy array manipulation: even newer tools like Pandas are built around the NumPy array.
This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays.
While the types of operations shown here may seem a bit dry and pedantic, they comprise the building blocks of many other examples used throughout the book.
Get to know them well!

Python中的數據操作基本就是NumPy數組操作的同義詞：一些新的工具像Pandas 都是依賴於NumPy數組建立起來的。本節會展示使用NumPy數組操作和訪問數據以及子數組的一些例子，包括切分、變形和組合。儘管這裡展示的操作有些枯燥和學術化，但是它們是組成本書後面使用的例子的基礎。你應該更好的掌握它們。


> - *Attributes*: Determining the size, shape, memory consumption, and data types of arrays
> - *Indexing & Slicing*: Getting and setting the value of individual array elements
> - *Reshaping*: Changing the shape of a given array
> - *Joining & Splitting*: Combining multiple arrays into one, and splitting one array into many

### 4.NumPy : Joining and splitting 數組的連接和切分

#### Concatenation of arrays 連接數組

> Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routines ``np.concatenate``, ``np.vstack``, and ``np.hstack``. ``np.concatenate`` takes a tuple or list of arrays as its first argument:

在NumPy中連接或者組合多個數組，有三個不同的方法`np.concatenate`，`np.vstack`和`np.hstack`。 `np.concatenate`接受一個數組的元組或列表作為第一個參數，如下：

In [1]:
import numpy as np
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr
arr * arr
arr - arr
1 / arr
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [2]:
arr1=np.array([2,4,6,8,2])
arr2=np.array([3,6,1,5,2])

arr1+arr2
arr1-arr2
arr1*arr2

array([ 6, 24,  6, 40,  4])

- np.concatenate

In [3]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [4]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [5]:
# It can also be used for two-dimensional arrays:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid, grid]) 

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [6]:
# 沿著第二個維度進行連接，即按照列連接，axis=1
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

- np.vstack 和 np.hstack : 進行連接的數組如果具有不同的維度，使用`np.vstack`（垂直堆疊）和`np.hstack`（水平堆疊）會更加清晰：

In [7]:
one = np.array([2,4,6,8])
two = np.array([1,2,3,4])
np.vstack((one,two))        # 沿著垂直堆疊

array([[2, 4, 6, 8],
       [1, 2, 3, 4]])

In [8]:
np.hstack((one,two))

array([2, 4, 6, 8, 1, 2, 3, 4])

In [9]:
np.column_stack((one,two))

array([[2, 1],
       [4, 2],
       [6, 3],
       [8, 4]])

In [10]:
grid = np.array([[9, 8, 7],[6, 5, 4]])
x = np.array([1, 2, 3])
np.vstack([x, grid])       # 沿著垂直堆疊

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [11]:
y = np.array([[99],[99]])
np.hstack([grid, y])       # 沿著水平堆疊

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

#### Splitting of arrays 切分數組

> The opposite of concatenation is splitting, which is implemented by the functions ``np.split``, ``np.hsplit``, and ``np.vsplit``.  For each of these, we can pass a list of indices giving the split points:

連接的反操作是切分，主要的方法包括`np.split`，`np.hsplit`和`np.vsplit`。我們可以傳遞一個列表參數表示切分的點：

In [12]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # 在序號3和序號5處進行切分，返回三個數組
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


- np.hsplit 和 np.vsplit

In [13]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
upper, lower = np.vsplit(grid, [2]) # 沿垂直方向切分，切分點行序號為2
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [15]:
left, right = np.hsplit(grid, [2]) # 沿水平方向切分数组，切分點列序號為2
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
